Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "file", source: "someFile", destination: "~/pythonTest/someFile"

  config.vm.provision "shell", inline: <<-SHELL

    sudo apt-get update -y
    sudo apt-get install -y python3 python3-pip python3-dev build-essential libpq-dev
    pip3 install psycopg2-binary Django
SHELL
end
